### PR TITLE
PSD image processing may cause unhandled panic

### PR DESCRIPTION
**Pull request by hellwege**
[why]
Earlier made to fix panic is not complete and can end up reading closed channel.

[how]
Correctly handle compress processing to wait for sub processing to finish before closing error channel.

[testing]
Manual, use earlier psd images which caused panic/crash, observe no panic.

### CODE REVIEW

**Comment by hellwege** [comment]
[IMG_0247.psd.zip](https://github.com/oov/psd/files/5626430/IMG_0247.psd.zip)
See attached which demonstrates issue.

**Comment by oov** [comment]
Your test file seems cause unrelated error.
```
psd: invalid image resource signature
````
This error already fix in https://github.com/oov/psd/commit/47a4ad607b94d23dad073cc18dfc3ea19860ea64.
I haven't encountered any panics around decoding, how do I test it?

**Comment by hellwege** [comment]
We integrate this library into a server which is long running. If your tool or test exists after it sees the first decoding error, then you won't encounter the issue. 
The issue occurs when there are multiple errors in the decoding.  The decodePackBits exists because of an earlier error, but the processing goroutine is still running and encounters another error.  This causes a write to the error channel which was previously closed.  The solution waits until all goroutines are finished, and only closes the error channel when they are done.

Perhaps the new commit you made also fixes the issue as it now properly decodes because of the correct resource signature.  However, the change is still valid as it ensures the goroutines are finished decoding before closing the error channel, which is clean.

**Comment by oov** [comment]
I understand for the validity of this PR.

But in the first place, I think #9 and #11 are heading in the wrong way for this issue.
I should have pointed to the right direction.
Sorry, it's my fault.

The package should not depend on panic because the encountering broken inputs is a normal situation.
So I reverted #9 and add some range checks in https://github.com/oov/psd/commit/dad9002861d9367c07ba1acaa5a7ddc55f9d1073.

The problems caused by panic during decoding would now be solved.
If this doesn't solve for you, contact me again.

Thanks.

**Comment by hellwege** [comment]
Ok, yes thank you.  Better to have input checks and avoid panics, then you don't need the panic processing.  Will check this out.

**Pull request closed without merging**
